export let products = [
  {
    id: "1",
    pName: "Cement (Portland)",
    specs: "",
    brand: "Holcim",
    category: "Cement and Concrete Products",
    priceInCents: 27550,
    image: "assets/cement.jpg",
  },
  {
    id: "2",
    pName: "Concrete Hollow Blocks (CHB)",
    specs: "",
    brand: "SSIC",
    category: "Cement and Concrete Products",
    priceInCents: 16342,
    image: "assets/Hollow-Block-Icon-1.png",
  },
  {
    id: "3",
    pName: "Grout",
    specs: "",
    brand: "ABC",
    category: "Cement and Concrete Products",
    priceInCents: 850,
    image: "assets/ABC-Tile-Grout-Original-1.png",
  },
  {
    id: "4",
    pName: "Mortar",
    specs: "",
    brand: "Bostik",
    category: "Cement and Concrete Products",
    priceInCents: 56455,
    image: "assets/mortar-bostik.png",
  },
  {
    id: "5",
    pName: "Sand",
    specs: "Fine",
    brand: "A&D Trading",
    category: "Aggregates",
    priceInCents: 7458,
    image: "assets/fine-sand.jpg",
  },
  {
    id: "6",
    pName: "Gravel",
    specs: "",
    brand: "A&D Trading",
    category: "Aggregates",
    priceInCents: 46414,
    image: "assets/gravel.jpeg",
  },
  {
    id: "7",
    pName: "Crushed(Stone)",
    specs: "",
    brand: "A&D Trading",
    category: "Aggregates",
    priceInCents: 9137,
    image: "assets/Crushed-Stone.jpg",
  },
  {
    id: "8",
    pName: "Laid Stone(Riprap)",
    specs: "",
    brand: "A&D Trading",
    category: "Aggregates",
    priceInCents: 13285,
    image: "assets/laid-stone-riprap.png",
  },
  {
    id: "9",
    pName: "Rebars 12mm",
    specs: "12mm",
    brand: "A&D Trading",
    category: "Steel and Metal Products",
    priceInCents: 33185,
    image: "../assets/rebars.jpg",
  },
  {
    id: "10",
    pName: "Rebars 10mm",
    specs: "10mm",
    brand: "A&D Trading",
    category: "Steel and Metal Products",
    priceInCents: 98644,
    image: "../assets/rebars.jpg",
  },
];
