export let products = [
  {
    id: "1",
    pName: "Cement(Portland)",
    specs: "",
    brand: "Holcim",
    category: "Cement and Concrete Products",
    price: 275,
    image: "",
  },
  {
    id: "2",
    pName: "Concrete Hollow Blocks (CHB)",
    specs: "",
    brand: "",
    category: "Cement and Concrete Products",
    price: 275,
    image: "",
  },
  {
    id: "3",
    pName: "Grout",
    specs: "",
    brand: "ABC",
    category: "Cement and Concrete Products",
    price: 275,
    image: "",
  },
  {
    id: "4",
    pName: "Mortar",
    specs: "",
    brand: "Bostik",
    category: "Cement and Concrete Products",
    price: 275,
    image: "",
  },
  {
    id: "5",
    pName: "Sand",
    specs: "Fine",
    brand: "",
    category: "Aggregates",
    price: 275,
    image: "",
  },
  {
    id: "6",
    pName: "Gravel",
    specs: "",
    brand: "",
    category: "Aggregates",
    price: 275,
    image: "",
  },
  {
    id: "7",
    pName: "Crushed(Stone)",
    specs: "",
    brand: "",
    category: "Aggregates",
    price: 275,
    image: "",
  },
  {
    id: "8",
    pName: "Laid Stone(Riprap)",
    specs: "",
    brand: "",
    category: "Aggregates",
    price: 275,
    image: "",
  },
  {
    id: "9",
    pName: "Reinforcing Steel Bars (Rebars)",
    specs: "12mm",
    brand: "",
    category: "Steel and Metal Products",
    price: 275,
    image: "",
  },
  {
    id: "10",
    pName: "Reinforcing Steel Bars (Rebars)",
    specs: "10mm",
    brand: "",
    category: "Steel and Metal Products",
    price: 275,
    image: "",
  },
];
